apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-upload-service-dev-worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca-upload-service-dev-worker
  template:
    metadata:
      labels:
        app: ca-upload-service-dev-worker
    spec:
      containers:
        - name: ca-upload-service-dev-worker
          image: 981666308374.dkr.ecr.us-west-1.amazonaws.com/ca-upload-service-dev:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: LOG_LEVEL
              value: "debug"
          imagePullPolicy: Always
      imagePullSecrets: 
        - name: regcred 
      containers:
      - name: api
        image: 981666308374.dkr.ecr.us-west-1.amazonaws.com/ca-agency-service-dev:latest
        command: [ "sleep" ]
        args: [ "infinity" ] 