apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-storage-class
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0b89327cb5056a100  # Replace with your actual volume ID
    fsType: ext4
   