apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: 981666308374.dkr.ecr.us-west-1.amazonaws.com/ca-agency-service-dev:latest
  imagePullSecrets:
  - name: secretcastingcreddev